language: objective-c
os: osx
osx_image: xcode10
rvm: 2.3

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
  - ${HOME}/unity_download_cache
  - ${HOME}/unity_build_cache

env:
  global:
  - UNITY_DOWNLOAD_CACHE=${HOME}/unity_download_cache
  - UNITY_BUILD_CACHE=${HOME}/unity_build_cache

jobs:
  include:
  - stage: build
    before_install:
    - chmod -R a+rw ${HOME}/unity_download_cache
    - chmod -R a+rw ${HOME}/unity_build_cache
    - chmod a+x ./travis-build/*.sh
    install: ./travis-build/install-unity.sh
    script: travis_wait 40 ./travis-build/build.sh
    after_success:
    - ls -al ${HOME}/unity_download_cache
    - ls -al ${HOME}/unity_build_cache
  - stage: deploy
    before_install:{
    - chmod -R a+rw ${HOME}/unity_build_cache
    - ls -al ${HOME}/unity_build_cache
    - openssl enc -aes-256-cbc -a -d -in ./travis-build/setup_ssh.sh.enc -out ./travis-build/setup_ssh.sh -k ${ENCRYPTION_PASSWORD}
    - chmod a+x ./travis-build/setup_ssh.sh
    - ./travis-build/setup_ssh.sh
    install: bundle install
    script: fastlane ios release