language: objective-c
os: osx
osx_image: xcode10

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  bundler: true
  directories:
  - unity_download_cache

env:
  global:
  - UNITY_DOWNLOAD_CACHE="${TRAVIS_BUILD_DIR}/unity_download_cache"
  
jobs:
  include:
  - stage: prepare cache
    script:
    - chmod -R a+rw ./unity_download_cache
    - openssl enc -aes-256-cbc -a -d -in ./travis-build/setup_ssh.sh.enc -out ./travis-build/setup_ssh.sh -k ${ENCRYPTION_PASSWORD}
    - chmod a+x ./travis-build/*.sh
    - ./travis-build/setup_ssh.sh
    - ./travis-build/install-unity.sh
    rvm: 2.3
  - stage: build
    script: travis_wait 50 ./travis-build/build.sh
  - stage: deploy
    script: fastlane ios release
    rvm: 2.3