language: objective-c
os: osx
osx_image: xcode10.2
rvm: 2.3

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
  - $HOME/unity_download_cache
  - $HOME/unity_build_cache

env:
  global:
  - UNITY_DOWNLOAD_CACHE="$HOME/unity_download_cache"
  - UNITY_BUILD_CACHE="$HOME/unity_build_cache"

jobs:
  include:
  - stage: build
    before_install:
    - chmod -R a+rw "${HOME}/unity_download_cache"
    - chmod -R a+rw "${HOME}/unity_build_cache"
    - chmod a+x ./travis-build/*.sh
    install: ./travis-build/install-unity.sh
    script:
    - travis_wait 40 ./travis-build/build.sh
    - ls -al "${HOME}/unity_download_cache"
    - ls -al "${HOME}/unity_build_cache"
  - stage: deploy mac
    before_install:
    - chmod -R a+rw "${HOME}/unity_build_cache"
    - ls -al "${HOME}/unity_build_cache"
    - sleep 10
    - chmod -R a+xr "${HOME}/unity_build_cache/OSX/Card Game Simulator.app"
    - chmod +x ./travis-build/setup-osx-certificates.sh
    - ./travis-build/setup-osx-certificates.sh
    - codesign -f --deep -s "3rd Party Mac Developer Application\: Finol Digital LLC" --entitlements "${TRAVIS_BUILD_DIR}/Assets/Editor/Card Game Simulator.entitlements" "${HOME}/unity_build_cache/OSX/Card Game Simulator.app"
    - productbuild --component "${HOME}/unity_build_cache/OSX/Card Game Simulator.app" /Applications --sign "3rd Party Mac Developer Installer\: Finol Digital LLC" "Card Game Simulator.pkg"
    - sleep 10
    install: bundle install
    script: travis_wait 40 fastlane mac macupload
#  - stage: deploy ios
#    before_install:
#    - chmod -R a+rw "${HOME}/unity_build_cache"
#    - ls -al "${HOME}/unity_build_cache"
#    - openssl enc -aes-256-cbc -a -d -in ./travis-build/setup_ssh.sh.enc -out ./travis-build/setup_ssh.sh -k ${ENCRYPTION_PASSWORD}
#    - chmod a+x ./travis-build/setup_ssh.sh
#    - ./travis-build/setup_ssh.sh
#    install: bundle install
#    script: travis_wait 50 fastlane ios release