language: objective-c
os: osx
osx_image: xcode10

rvm:
- 2.2

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
- chmod a+x ./travis-build/*.sh

install:
- cat /etc/hosts
- ./travis-build/install-unity.sh

script:
- ./travis-build/build.sh
