language: objective-c
os: osx
osx_image: xcode10

rvm:
- 2.2

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
- bundle install
- openssl enc -aes-256-cbc -a -d -in ./travis-build/setup_ssh.sh.enc -out ./travis-build/setup_ssh.sh -k ${ENCRYPTION_PASSWORD}
- chmod a+x ./travis-build/*.sh
- . ./travis-build/setup_ssh.sh

install:
- ./travis-build/install-unity.sh

script:
- travis_wait 50 ./travis-build/build.sh

after_success:
- fastlane ios beta