language: objective-c
os: osx
osx_image: xcode10.2
rvm: 2.3

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
  - $HOME/unity_download_cache
  - $HOME/unity_build_cache

env:
  global:
  - UNITY_DOWNLOAD_CACHE="$HOME/unity_download_cache"
  - UNITY_BUILD_CACHE="$HOME/unity_build_cache"

stages:
  - build
  - name: deploy mobile
    if: branch = master
  - name: deploy desktop
    if: branch = develop

jobs:
  include:
  - stage: build
    before_install:
    - chmod -R a+rw "${HOME}/unity_download_cache"
    - chmod -R a+rw "${HOME}/unity_build_cache"
    - chmod a+x ./travis-build/*.sh
    install: ./travis-build/install-unity.sh
    script:
    - travis_wait 45 ./travis-build/build.sh
    - ls -al "${HOME}/unity_download_cache"
    - ls -al "${HOME}/unity_build_cache"
  - stage: deploy mobile
#    env: ALLOW_DEPLOY_TIMEOUT=true
    before_install:
    - chmod -R a+rw "${HOME}/unity_build_cache"
    - ls -al "${HOME}/unity_build_cache"
    - openssl enc -aes-256-cbc -a -d -in ./travis-build/setup_ssh.sh.enc -out ./travis-build/setup_ssh.sh -k ${ENCRYPTION_PASSWORD}
    - chmod a+x ./travis-build/setup_ssh.sh
    - ./travis-build/setup_ssh.sh
    install: bundle install
    script: travis_wait 45 fastlane ios release
  - stage: deploy desktop
    before_install:
    - chmod -R a+rw "${HOME}/unity_build_cache"
    - ls -al "${HOME}/unity_build_cache"
    - chmod +x ./travis-build/sign-osx-build.sh
    - ./travis-build/sign-osx-build.sh
    install: bundle install
    script: travis_wait 45 fastlane mac macupload

matrix:
  allow_failures:
    - env: ALLOW_DEPLOY_TIMEOUT=true