plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
title: Card Game Simulator
description: Play your favorite card games!
url: 'https://www.cardgamesimulator.com'
theme: jekyll-theme-slate
include: [".well-known", "*.unityweb", ]
