plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
title: Card Game Simulator
description: Play your favorite card games!
url: 'https://www.cardgamesimulator.com'
show_downloads: false
theme: jekyll-theme-slate
