name: Build and Release CGS
on:
  pull_request: { branches: [master] }
  push: { branches: [master] }
  release: { types: [published] }
env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
jobs:
  buildForAllPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2018.4.20f1
        targetPlatform:
          - Android # Build an Android .apk standalone app.
          - iOS # Build an iOS player.
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
#          - WSAPlayer # Build an Windows Store Apps player.
#          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: create android keystore
        run: |
          echo "${{ secrets.UNITY_ANDROID_KEYSTORE }}" > finoldigital.keystore.asc
          gpg -d --passphrase "${{ secrets.UNITY_ANDROID_KEYSTORE_PASS }}" --batch finoldigital.keystore.asc > finoldigital.keystore
      - uses: webbertakken/unity-builder@v0.11
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: builds
          buildMethod: BuildCGS.BuildProject
          customParameters: -androidAppBundle -keystorePass ${{ secrets.UNITY_ANDROID_KEYSTORE_PASS }} -keyaliasPass ${{ secrets.UNITY_ANDROID_KEYSTORE_PASS }}
      - uses: actions/upload-artifact@v1
        with:
          name: cgs-builds
          path: builds
  releaseToStore:
    name: Release to Google Play and the App Store
    runs-on: macOS-latest
    needs: buildForAllPlatforms
    if: github.event.action == 'published'
    env:
      APPLE_CONNECT_EMAIL: ${{ secrets.APPLE_CONNECT_EMAIL }}
      APPLE_DEVELOPER_EMAIL: ${{ secrets.APPLE_DEVELOPER_EMAIL }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_TEAM_NAME: ${{ secrets.APPLE_TEAM_NAME }}
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      GOOGLE_PLAY_KEY_FILE_PATH: ${{ secrets.GOOGLE_PLAY_KEY_FILE_PATH }}
      MAC_APPLICATION_CERTIFICATE: ${{ secrets.MAC_APPLICATION_CERTIFICATE }}
      MAC_APPLICATION_PASSWORD: ${{ secrets.MAC_APPLICATION_PASSWORD }}
      MAC_INSTALLER_CERTIFICATE: ${{ secrets.MAC_INSTALLER_CERTIFICATE }}
      MAC_INSTALLER_PASSWORD: ${{ secrets.MAC_INSTALLER_PASSWORD }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_PERSONAL_ACCESS_TOKEN: ${{ secrets.MATCH_PERSONAL_ACCESS_TOKEN }}
      MATCH_URL: ${{ secrets.MATCH_URL }}
      BUILDS_PATH: ${{ format('{0}/builds', github.workspace) }}
      ANDROID_PACKAGE_NAME: com.finoldigital.cardgamesim
      IOS_APP_ID: com.finoldigital.CardGameSim
      MAC_APP_ID: com.finoldigital.CardGameSimulator
      MAC_APP_BUNDLE_PATHS: Contents/Plugins/libProcessStart.bundle;Contents/Plugins/FileBrowser.bundle
      PROJECT_NAME: Card Game Simulator
      RELEASE_NOTES: ${{ github.event.release.body }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/download-artifact@v1
        with:
          name: cgs-builds
          path: builds
#      - run: echo "${{ secrets.GOOGLE_PLAY_KEY_FILE }}" > ${{ secrets.GOOGLE_PLAY_KEY_FILE_PATH }}
#      - uses: maierj/fastlane-action@v1.4.0
#        with:
#          lane: 'android playstore'
      - run: find $BUILDS_PATH -type f -iname "*.sh" -exec chmod +x {} \;
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'ios release'
      - run: |
          chmod +x fastlane/sign-osx-build.sh
          ./fastlane/sign-osx-build.sh
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'mac macupload'
