name: Build and Release CGS
on:
  pull_request: { branches: [master] }
  push: { branches: [master] }
  release: { types: [published] }
env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
jobs:
  buildForAllPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2018.4.19f1
        targetPlatform:
#          - Android # Build an Android .apk standalone app.
          - iOS # Build an iOS player.
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
#          - WSAPlayer # Build an Windows Store Apps player.
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: |
          echo "${{ secrets.UNITY_ANDROID_KEYSTORE }}" > finoldigital.keystore.asc
          gpg -d --passphrase "${{ secrets.UNITY_ANDROID_KEYSTORE_PASS }}" --batch finoldigital.keystore.asc > finoldigital.keystore
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
      - uses: webbertakken/unity-builder@v0.11
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: builds
          buildMethod: BuildCGS.BuildProject
          customParameters: -androidAppBundle -keystorePass ${{ secrets.UNITY_ANDROID_KEYSTORE_PASS }} -keyaliasPass ${{ secrets.UNITY_ANDROID_KEYSTORE_PASS }}
      - uses: actions/upload-artifact@v1
        with:
          name: cgs-builds
          path: builds
  releaseToStore:
    name: Release to Google Play and the App Store
    runs-on: macOS-latest
    needs: buildForAllPlatforms
#    if: github.event.release.published
    env:
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/download-artifact@v1
        with:
          name: cgs-builds
          path: builds
      - run: |
          bundle install
#          bundle exec fastlane android playstore
          bundle exec fastlane ios release
#          chmod +x fastlane/sign-osx-build.sh
#          ./fastlane/sign-osx-build.sh
#          bundle exec fastlane mac macupload
