name: Build and Release CGS
on:
  push: { branches: [develop, master] }
  pull_request: { branches: [master] }
  release: { types: [published] }
jobs:
  buildForAllPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.1f1
        targetPlatform:
          - Android # Build an Android .apk standalone app.
          - iOS # Build an iOS player.
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
#          - WSAPlayer # Build a Universal Windows Platform (UWP) app.
#          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
      - uses: davidmfinol/unity-builder@4bbcbe6395a50f6afe3576a4371126cd998055c5
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: builds
          androidAppBundle: true
          androidKeystoreName: finoldigital.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
      - uses: actions/upload-artifact@v1
        if: github.event.ref != 'refs/heads/develop'
        with:
          name: cgs-builds
          path: builds
  releaseToStore:
    name: Release to Google Play and the App Store
    runs-on: macOS-latest
    needs: buildForAllPlatforms
    if: github.event.action == 'published'
    env:
      APPLE_CONNECT_EMAIL: ${{ secrets.APPLE_CONNECT_EMAIL }}
      APPLE_DEVELOPER_EMAIL: ${{ secrets.APPLE_DEVELOPER_EMAIL }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_TEAM_NAME: ${{ secrets.APPLE_TEAM_NAME }}
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      GOOGLE_PLAY_KEY_FILE: ${{ secrets.GOOGLE_PLAY_KEY_FILE }}
      MAC_APPLICATION_CERTIFICATE: ${{ secrets.MAC_APPLICATION_CERTIFICATE }}
      MAC_APPLICATION_PASSWORD: ${{ secrets.MAC_APPLICATION_PASSWORD }}
      MAC_INSTALLER_CERTIFICATE: ${{ secrets.MAC_INSTALLER_CERTIFICATE }}
      MAC_INSTALLER_PASSWORD: ${{ secrets.MAC_INSTALLER_PASSWORD }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_PERSONAL_ACCESS_TOKEN: ${{ secrets.MATCH_PERSONAL_ACCESS_TOKEN }}
      MATCH_URL: ${{ secrets.MATCH_URL }}
      BUILDS_PATH: ${{ format('{0}/builds', github.workspace) }}
      GOOGLE_PLAY_KEY_FILE_PATH: ${{ format('{0}/fastlane/api-finoldigital.json', github.workspace) }}
      ANDROID_PACKAGE_NAME: com.finoldigital.cardgamesim
      IOS_APP_ID: com.finoldigital.CardGameSim
      MAC_APP_ID: com.finoldigital.CardGameSimulator
      MAC_APP_BUNDLE_PATHS: Contents/Plugins/libProcessStart.bundle;Contents/Plugins/FileBrowser.bundle
      PROJECT_NAME: Card Game Simulator
      RELEASE_NOTES: ${{ github.event.release.body }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/download-artifact@v1
        with:
          name: cgs-builds
          path: builds
      - name: Prepare for upload
        run: |
          echo "$GOOGLE_PLAY_KEY_FILE" > $GOOGLE_PLAY_KEY_FILE_PATH
          echo "$RELEASE_NOTES" > fastlane/metadata/android/en-US/changelogs/default.txt
          find $BUILDS_PATH -type f -iname "*.sh" -exec chmod +x {} \;
          chmod +x fastlane/sign-osx-build.sh
          ./fastlane/sign-osx-build.sh
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'android playstore'
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'ios release'
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'mac macupload'
